#! /usr/bin/env python3
import os
import sys

try:
    from argparse import ArgumentParser
except:
    err = """
    You haven't installed the required dependencies.
    Run 'python setup.py install' to install the dependencies.
    """
    print(err)
    sys.exit(0)

coolkit_help="""usage coolkit [option] [--suboptions [args]]
"""

def extract_args(args):
    first_arg = None
    if(len(sys.argv) > 1):
        argv_new = [sys.argv[0]]
        first_arg = sys.argv[1]
        if(len(sys.argv) > 2):
            argv_new.extend(sys.argv[2:])
        sys.argv = argv_new
    else:
        print(coolkit_help)
        sys.exit(0)

    if(first_arg not in args):
        print(coolkit_help)
    return first_arg

def parse_args():
    args = ['init','set','run','fetch','submit','config','list_args']
    first_arg = extract_args(args)
    parser = ArgumentParser()
    if(first_arg == "init"):
        parser.add_argument('-c',"--contest",
                            dest='contest',
                            default = 'None',
                            help="contest num ex: 1080, 987, 840")
        parser.add_argument('-t',"--type",
                            dest = 'type',
                            default = 'contest',
                            help="contest type")
        parser.add_argument('-p',"--prob",
                            dest = 'prob',
                            default = 'A',
                            help="problem seq ex: A, B, C")
        parser.add_argument('-s',"--site",
                            dest = 'site',
                            default='https://codeforces.com',
                            help="contest_site full link ex: https://codeforces.com")

    elif(first_arg == "set"):
        parser.add_argument('-c',"--contest",
                            dest='contest',
                            help="contest num ex: 1080, 987, 840")
        parser.add_argument('-t',"--type",
                            dest = 'type',
                            help="contest type")
        parser.add_argument('-p',"--prob",
                            dest = 'prob',
                            help="problem seq ex: A, B, C")
        parser.add_argument('-s',"--site",
                            dest = 'site',
                            help="contest_site full link ex: https://codeforces.com")

    elif(first_arg == "run"):
        parser.add_argument('-i',"--input",
                            dest='test',
                            type=int,
                            default = 0,
                            help="test_case num")
        parser.add_argument('-t',"--test",
                            dest='test',
                            type=int,
                            default = 0,
                            help="test_case num")
        parser.add_argument('-p',"--prob",
                            dest = 'prob',
                            help="problem seq ex: A, B, C")

    elif(first_arg == "fetch"):
        parser.add_argument('-c',"--contest",
                            dest='contest',
                            help="contest num ex: 1080, 987, 840")
        parser.add_argument('-t',"--type",
                            dest = 'type',
                            default = 'contest',
                            help="contest type")
        parser.add_argument('-s',"--site",
                            dest = 'site',
                            default='https://codeforces.com',
                            help="contest_site full link ex: https://codeforces.com")

    elif(first_arg == "submit"):
        parser.add_argument('-c',"--contest",
                            dest='contest',
                            help="contest num ex: 1080, 987, 840")
        parser.add_argument('-t',"--type",
                            dest = 'type',
                            help="contest type")
        parser.add_argument('-p',"--prob",
                            dest = 'prob',
                            help="problem seq ex: A, B, C")
        parser.add_argument('-s',"--site",
                            dest = 'site',
                            help="contest_site full link ex: https://codeforces.com")

    elif(first_arg == "config"):
        parser.add_argument('-u',"--user",
                            dest='user',
                            help="username/handle")
        parser.add_argument('-p',"--pass",
                            dest = 'pass',
                            help="password")

    elif(first_arg == "list_args"):
        print(" ".join(sorted(args[:-1])))
        return

    print(parser.parse_args())

if __name__ == '__main__':
    parse_args()
